INSERT INTO Questions 
	(id, questionText) 
VALUES 
	(1, 'Which Noah is the best Noah?'),
	(2, 'Which of these things will Peanut the dog NOT eat?'),
	(3, 'Why do I live with a cat named Shelly?'),
	(4, 'How much wood could a woodchuck chuck if a woodchuck could chuck wood?'),
	(5, 'What does Thomas like to do best in his spare time?'),
	(6, 'What if you woke up one morning and had spaghetti for hair?'),
	(7, 'What would you like to drink?'),
	(8, "You get home late at night and flip on the lights. There, sitting on your couch, is a man you've never seen before. You:"),
	(9, "What is Thomas's favorite way to exercise?"),
	(10, 'True or false: SumoMe was inspired by real-life, actual sumo wrestler, Takanoyama Shuntaro, the only professional Czech sumo wrestler in history.');

INSERT INTO Choices
	(QuestionId, choiceText)
VALUES
	(1, 'Facebook Noah'),
	(1, 'Mint Noah'),
	(1, 'Gambit Noah'),
	(1, 'SumoMe Noah'),
	(1, 'All Noahs'),
	(2, 'Apples'),
	(2, 'Bananas'),
	(2, 'Cat poop'),
	(2, 'Dog poop'),
	(2, 'Lettuce'),
	(3, 'I love animals'),
	(3, "She was my wife's cat"),
	(3, 'I hate myself'),
	(3, 'I love terrible smells'),
	(3, 'I am raising her for food'),
	(4, 'Too much'),
	(4, 'Not enough'),
	(4, 'Did you know they are also known as whistlepigs, can swim really well, and generally like being huge jerks to one another? Also yeah I have no idea.'),
	(5, 'Watch TV'),
	(5, 'Read'),
	(5, 'Sleep'),
	(5, 'Play video games'),
	(5, 'Do code challenges given to him by Noah'),
	(6, "That's weird"),
	(6, "That's fine"),
	(6, "BUT I'M GLUTEN-FREE"),
	(6, 'Is it vegan? Asking for wife'),
	(7, 'Water is fine'),
	(7, "I'll have a diet coke"),
	(7, "A margarita on the rocks, please"),
	(7, "Peanut butter"),
	(8, 'Introduce yourself'),
	(8, "Ask him what he's doing"),
	(8, 'Slowly back away'),
	(8, 'Run'),
	(8, 'Jump into his lap'),
	(8, 'Kiss him in his left ear'),
	(9, 'Walking Peanut the dog'),
	(9, 'Running'),
	(9, 'Lifting'),
	(9, 'Pole dancing'),
	(9, 'Doing the Jingle Bell Rock dance from the movie Mean Girls in his boxer briefs with friends'),
	(10, 'True'),
	(10, 'False');
